zarzadzanie/main/urls.py
from django.urls import path, include
from .views import start, zadania, details, \
    add_task, check_task, edytuj_task, add_projekt, \
    delete_task, remove_task, done_task, add_users, \
    rejestracja, logowanie, wylogowanie, login_view, lista_zadan_choice
from django.contrib.auth import views as auth_views



app_name = 'main'
urlpatterns = [
    path('<int:projekt_id>', zadania, name="zadania"),
    path('main/<int:zadanie_id>', check_task, name="check_task"),

    path('main/details', details, name="details"),
    path('main/add_task', add_task, name="add_task"),
    path('main/add_projekt', add_projekt, name="add_projekt"),
    path('main/add_users', add_users, name="add_users"),
    path('main/edytuj_task/<int:id>/', edytuj_task, name="edytuj_task"),
    path('main/remove_task/<int:zadanie_id>/', remove_task, name="remove_task"),
    path('main/delete_task/<int:projekt_id>/', delete_task , name="delete_task"),
    path('main/done_task/<int:projekt_id>/', done_task , name="done_task"),
    path('main/rejestracja', rejestracja, name="rejestracja"),
    path('main/login', login_view, name="login"),
    path('main/wylogowanie', wylogowanie , name="wylogowanie"),
    # path('main/login', auth_views.LoginView.as_view(), name="login"),
    path('main/logout', auth_views.LogoutView.as_view(), name="logout"),
    path('', start, name="start"),
    path('main/test', lista_zadan_choice,name='lista_zadan_choice')

]
# urlpatterns += [
#     path('accounts/', include('django.contrib.auth.urls')),
# ]

zarzadzanie/zarzadzanie/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('task', include('task.urls')),
    path('', include('main.urls')),

    # path('login/', auth_views.LoginView.as_view(), name="login"),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),

]

zarzadzanie/main/models.py
from django.db import models

zarzadzanie/main/views.py
from django.shortcuts import HttpResponse, render, get_list_or_404, redirect
from task.models import Task, Projects
from django.forms import ModelForm
from django import forms
from django.db.models import Sum
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import (authenticate, get_user_model, login, logout)

# from .models import Task

global no_project



User = get_user_model()

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')

        return super(UserLoginForm, self).clean(*args, **kwargs)

class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label='Email address')
    email2 = forms.EmailField(label='confirm address')
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'email2',
            'password'
        ]

    def clean_email(self):

        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        if email != email2:
            raise forms.ValidationError("emails must match")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError(
                "This email is already being used"
            )
        return email



def login_view(request):

    global numer_usera
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)

    if form.is_valid():

        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        print('logowanie')
        uzytkownik = User.objects.get(username=username)
        numer_usera = uzytkownik.id
        projects = Projects.objects.filter(user=uzytkownik.id)
        contex = {"projects": projects, "user_id": uzytkownik.id}
        if next:
            return redirect(next)
        return render(request,'strona_startowa.html', contex)

    contex = {
        'form': form,
    }
    return render(request, "login.html", contex)


class MySignUpForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(MySignUpForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['username']

        if commit:
            user.save()

        return user
class WeightForm(ModelForm):
    class Meta:
        fields = ['']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

def wylogowanie(request):
    obj = 'something'
    print('wylogowanie')
    return redirect('https://google.com')

def logowanie(request):
    pass
    # if request.method == "POST":
    #     username = request.POST.get('username')
    #     password = request.POST.get('password')
    #
    #     user = authenticate(request, username=username, password=password)
    #
    #     if user is not None:
    #         login(request, user)
    #         contex = {'logowanie': 'ok'}
    #         print('wszystko dziala')
    #         print(f"drukowanie usera w konsoli zalogowanego {user.username}")
    #         # return redirect('strona_startowa.html')
    #         messages.success(request, f"Uzytkownik {user} został zalogowany")
    #         return render(request, 'main/strona_startowa.html', contex)
    # contex = {}
    #
    # return render(request, 'main/login.html', contex)

def rejestracja(request):

    if request.method == 'POST':
        form = MySignUpForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, "Konto zostało założone dla " + user)

    form = MySignUpForm()
    contex = {'form': form}
    return render(request, 'main/register.html', contex)





class ProjektForm(ModelForm):
    class Meta:
        model = Projects
        fields = ['project']

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields =['title', 'task', 'branch', 'timeneed', 'weight', 'level', 'status', 'timedone']

def add_users(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.save()

    return render(request, 'main/add_users.html', {'form': form})

@login_required
def start(request):
    try:
        global numer_usera

        projects = Projects.objects.filter(user=numer_usera)
    except:
        projects = None

    return render(request, "strona_startowa.html", {"projects": projects})

@login_required
def zadania(request, projekt_id: int):

    global no_project
    no_project = projekt_id
    poziom = "Wszystkie"
    waga = "Wszystkie"
    projekt = Projects.objects.filter(id=no_project)
    name_of_projekt = projekt[0].project
    suma_need = Task.objects.filter(projekt_id=no_project).exclude(status=2).aggregate(Sum('timeneed'))
    zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2)

    if suma_need['timeneed__sum'] != None:

        suma_done_min = Task.objects.filter(projekt_id=no_project).exclude(status=2).aggregate(Sum('timedone'))
        suma_done_done = Task.objects.filter(projekt_id=no_project, status=2).aggregate(Sum('timedone'))

        if suma_done_done["timedone__sum"] == None:
            suma_done_done["timedone__sum"] = 0

        suma_done = round(float((suma_done_min["timedone__sum"]/60)) + float((suma_done_done["timedone__sum"] / 60)), 2)
        suma_czas_do_skonczenia = round((suma_need["timeneed__sum"] - suma_done_min["timedone__sum"])/60, 2)
        info_o_zadaniach = ""
    else:
        suma_czas_do_skonczenia = 0
        suma_done = 0
        info_o_zadaniach = "DODAJ ZADANIE"



# ----------------- filtrów zadania względem wagi ----------------
    # weight_list = ['minor', 'major', 'critical']
    if request.method == 'POST':
        weight = request.POST.getlist('weight')
        print(weight)
        if weight == ['Minor']:
            print('wybrano minor')
            zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2, weight=0)
            waga = "Minor"
        elif weight == ['Major']:
            zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2, weight=1)
            waga = "Major"
        elif weight == ['Critical']:
            zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2, weight=2)
            waga = "Critical"
        elif weight == ['Minor', 'Major']:
            zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2, weight__lt=2)
            waga = "Minor, Major"
        elif weight == ['Minor', 'Critical']:
            zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2)
            zadania = zadania.exclude(weight=1)
            waga = "Minor, Critical"
        elif weight == ['Major', 'Critical']:
            zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2, weight__gt=0)
            waga = "Major, Critical"

        else:
            zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2)
            waga = "Wszystkie"

# ------------------- filtruje zadania względem poziomu trudności ---------------------------

        level = request.POST.getlist('level')

        if level == ['Easy']:
            print('wybrano easy')
            zadania = zadania.filter(level=0)
            poziom = "Easy"
        elif level == ['Medium']:
            zadania = zadania.filter(level=1)
            poziom = "Medium"
        elif level == ['Hard']:
            zadania = zadania.filter(level=2)
            poziom = "Hard"
        elif level == ['Easy', 'Medium']:
            zadania = zadania.filter(level__lt=2)
            poziom = "Easy, Medium"
        elif level == ['Easy', 'Hard']:
            zadania = zadania.exclude(level=1)
            poziom = "Easy, Hard"
        elif level == ['Medium', 'Hard']:
            zadania = zadania.filter(level_gt=1)
            poziom = "Medium, Hard"

        else:
            poziom = "Wszystkie"

    contex = {"zadania": zadania, "nr_projektu": projekt_id, "side": "show",
              "time_need": suma_czas_do_skonczenia, "time_done": suma_done, "is_task": info_o_zadaniach,
              "nazwa_projektu": name_of_projekt, "waga": waga, "poziom": poziom}

    return render(request, "main/lista_zadan.html", contex)






def details(request):

    return render(request, "main/details.html")

def add_task(request):
    global no_project
    form = TaskForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.projekt_id = no_project

        obj.save()



        zadania = Task.objects.all().filter(projekt=no_project, status__lt=2)
        contex = {"zadania": zadania, "nr_projektu": no_project, "side": "show"}

zarzadzanie/main/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/fc894043df.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">-->

    <title>{% block title %} {% endblock %}</title>
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
    {% block styles %} {%  endblock %}

</head>
<body>


  {%  block content %}
    {% endblock %}

</body>

zarzadzanie/main/templates/login.html
{% extends 'base.html'%}
{% load static %}

{% block title %}logowanie{% endblock %}
{% block content %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<div class="topnav">
  <a href="{% url 'main:start' %}">lista projektów</a>
  <a class="active" href="#contact">Logowanie użytkownika</a>
    <a href="{% url 'main:rejestracja' %}">Dodaj użytkownika</a>
<!--  <a href="#about">About</a>-->
</div>
<br>

<div> test </div>
<div class="card" style="width: 26rem;">
      <div class="card-body">
        <h5 class="card-title">Zaloguj się</h5>
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">Zaloguj <i class="fas fa-sign-in-alt"></i></button>
        </form>
      </div>
    </div>

{% endblock %}

zarzadzanie/main/templates/strona_startowa.html
{% extends 'base.html'%}
{% load static %}


{% block title %}główna{% endblock %}
{% block content %}

<div class="topnav">
  <a class="active" href="{% url 'main:start'  %}">lista projektów</a>
  <a href="{% url 'main:add_projekt' %}">Dodaj projekt</a>
  <a href="{% url 'main:rejestracja' %}">Dodaj użytkownika</a>
  <a href="{% url 'main:login' %}">Zaloguj się</a>
  <a href="{% url 'main:logout' %}">Wyloguj</a>

<!--  <a href="{% url 'main:details' %}">Contact</a>-->
<!--  <a href="#about">About</a>-->
</div>
<div>
    {% if user.is_authenticated %}
    <h1 class="display-4"> Witaj {{ user.username }}</h1>
{#    <a href="{% url 'logout' %}" class="btn btn-success">Logout <i class="fas fa-sign-out-alt"></i></a>#}
{% else %}
        <br><div>Nie jesteś zalogowany </div><br>
{% endif %}
uwaga {{  user_id }}

</div>

<div id="messages">
   {% for message in messages %}
        {{ message }}
   {% endfor %}
</div>

<div>
Wybierz projekt
  <br><br>
</div>
<table id="customers">
  <tr>
    <th class="lp">Lp</th>
    <th>Project</th>
    <th>donetime</th>
    <th>needtime</th>
  </tr>

  {% for projekt in projects %}

  <tr class="lp">
    <td class="lp">{{ forloop.counter }}</td>
    <td><a href="{%  url 'main:zadania' projekt.id %}">{{ projekt.project }}</a></td>

  </tr>
  {% endfor %}

</table>


{% endblock %}