zarzadzanie/main/urls.py
from django.urls import path, include
from .views import start, zadania, details, \
    add_task, check_task, edytuj_task, add_projekt, \
    delete_task, remove_task, done_task, add_users, \
    rejestracja, logowanie, wylogowanie, login_view, lista_zadan_choice
from django.contrib.auth import views as auth_views



app_name = 'main'
urlpatterns = [
    path('<int:projekt_id>', zadania, name="zadania"),
    path('main/<int:zadanie_id>', check_task, name="check_task"),

    path('main/details', details, name="details"),
    path('main/add_task', add_task, name="add_task"),
    path('main/add_projekt', add_projekt, name="add_projekt"),
    path('main/add_users', add_users, name="add_users"),
    path('main/edytuj_task/<int:id>/', edytuj_task, name="edytuj_task"),
    path('main/remove_task/<int:zadanie_id>/', remove_task, name="remove_task"),
    path('main/delete_task/<int:projekt_id>/', delete_task , name="delete_task"),
    path('main/done_task/<int:projekt_id>/', done_task , name="done_task"),
    path('main/rejestracja', rejestracja, name="rejestracja"),
    path('main/login', login_view, name="login"),
    path('main/wylogowanie', wylogowanie , name="wylogowanie"),
    # path('main/login', auth_views.LoginView.as_view(), name="login"),
    path('main/logout', auth_views.LogoutView.as_view(), name="logout"),
    path('', start, name="start"),
    path('main/test', lista_zadan_choice,name='lista_zadan_choice')

]
# urlpatterns += [
#     path('accounts/', include('django.contrib.auth.urls')),
# ]

zarzadzanie/zarzadzanie/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('task', include('task.urls')),
    path('', include('main.urls')),

    # path('login/', auth_views.LoginView.as_view(), name="login"),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),

]

zarzadzanie/main/models.py
from django.db import models

zarzadzanie/task/models.py
from django.db import models
from .database import Database as Db



class Uzytkownik(models.Model):
    pass


class Projects(models.Model):
    project = models.CharField(max_length=255, blank=True, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.id} - {self.project}, {self.user}"

class Weight():

     MINOR, MAJOR, CRITICAL = 0, 1, 2
     WEIGHT = ((MINOR, 'Minor'), (MAJOR, 'Major'), (CRITICAL, 'Critical'))

class Level():

    EASY, MEDIUM, HARD = 0, 1, 2
    LEVEL = ((EASY, 'Easy'), (MEDIUM, 'Medium'), (HARD, 'Hard'))

class Status():

    NOT_STARTED, IN_PROGRESS, DONE = 0, 1, 2
    STATUS = ((NOT_STARTED, 'Not started'), (IN_PROGRESS, 'In progress'), (DONE, 'Done'))

class Branch():

    TODO, POTTENTIAL_ERRORS, FOUND, IMPLEMENTATIONS, CSS = 0, 1, 2, 3, 4
    BRANCH = ((TODO, 'todo'), (POTTENTIAL_ERRORS, 'potencjalne błedy użytkownika'), (FOUND, 'znalezione błędy'),
              (IMPLEMENTATIONS, 'usprawnienia'), (CSS, 'CSS'))

class Task(models.Model):

    title = models.CharField(max_length=255, unique=True)
    task = models.TextField()
    branch = models.PositiveSmallIntegerField(choices=Branch.BRANCH, default=0)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    timeneed = models.IntegerField()
    timedone = models.DecimalField(max_digits=6, decimal_places=2,default=0)
    weight = models.PositiveSmallIntegerField(choices=Weight.WEIGHT, default=0)
    level = models.PositiveSmallIntegerField(choices=Level.LEVEL, default=0)
    status = models.PositiveSmallIntegerField(choices=Status.STATUS, default=0)
    projekt = models.ForeignKey(Projects, on_delete=models.CASCADE, default=None)
    timeusing = models.IntegerField(blank=True, default=0)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.id} - {self.title} : {self.created}"

zarzadzanie/main/views.py
from django.shortcuts import HttpResponse, render, get_list_or_404, redirect
from task.models import Task, Projects
from django.forms import ModelForm
from django import forms
from django.db.models import Sum
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import (authenticate, get_user_model, login, logout)

# from .models import Task

global no_project



User = get_user_model()

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')

        return super(UserLoginForm, self).clean(*args, **kwargs)

class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label='Email address')
    email2 = forms.EmailField(label='confirm address')
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'email2',
            'password'
        ]

    def clean_email(self):

        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        if email != email2:
            raise forms.ValidationError("emails must match")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError(
                "This email is already being used"
            )
        return email



def login_view(request):

    global numer_usera
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)

    if form.is_valid():

        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        print('logowanie')
        uzytkownik = User.objects.get(username=username)
        numer_usera = uzytkownik.id
        projects = Projects.objects.filter(user=uzytkownik.id)
        contex = {"projects": projects, "user_id": uzytkownik.id}
        if next:
            return redirect(next)
        return render(request,'strona_startowa.html', contex)

    contex = {
        'form': form,
    }
    return render(request, "login.html", contex)


class MySignUpForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(MySignUpForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['username']

        if commit:
            user.save()

        return user
class WeightForm(ModelForm):
    class Meta:
        fields = ['']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

def wylogowanie(request):
    obj = 'something'
    print('wylogowanie')
    return redirect('https://google.com')

def logowanie(request):
    pass
    # if request.method == "POST":
    #     username = request.POST.get('username')
    #     password = request.POST.get('password')
    #
    #     user = authenticate(request, username=username, password=password)
    #
    #     if user is not None:
    #         login(request, user)
    #         contex = {'logowanie': 'ok'}
    #         print('wszystko dziala')
    #         print(f"drukowanie usera w konsoli zalogowanego {user.username}")
    #         # return redirect('strona_startowa.html')
    #         messages.success(request, f"Uzytkownik {user} został zalogowany")
    #         return render(request, 'main/strona_startowa.html', contex)
    # contex = {}
    #
    # return render(request, 'main/login.html', contex)

def rejestracja(request):

    if request.method == 'POST':
        form = MySignUpForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, "Konto zostało założone dla " + user)

    form = MySignUpForm()
    contex = {'form': form}
    return render(request, 'main/register.html', contex)





class ProjektForm(ModelForm):
    class Meta:
        model = Projects
        fields = ['project']

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields =['title', 'task', 'branch', 'timeneed', 'weight', 'level', 'status', 'timedone']

def add_users(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.save()

    return render(request, 'main/add_users.html', {'form': form})

@login_required
def start(request):
    try:
        global numer_usera

        projects = Projects.objects.filter(user=numer_usera)
    except:
        projects = None

    return render(request, "strona_startowa.html", {"projects": projects})

@login_required
def zadania(request, projekt_id: int):

    global no_project
    no_project = projekt_id
    poziom = "Wszystkie"
    waga = "Wszystkie"
    projekt = Projects.objects.filter(id=no_project)
    name_of_projekt = projekt[0].project
    suma_need = Task.objects.filter(projekt_id=no_project).exclude(status=2).aggregate(Sum('timeneed'))
    zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2)

    if suma_need['timeneed__sum'] != None:

        suma_done_min = Task.objects.filter(projekt_id=no_project).exclude(status=2).aggregate(Sum('timedone'))
        suma_done_done = Task.objects.filter(projekt_id=no_project, status=2).aggregate(Sum('timedone'))

        if suma_done_done["timedone__sum"] == None:
            suma_done_done["timedone__sum"] = 0

        suma_done = round(float((suma_done_min["timedone__sum"]/60)) + float((suma_done_done["timedone__sum"] / 60)), 2)
        suma_czas_do_skonczenia = round((suma_need["timeneed__sum"] - suma_done_min["timedone__sum"])/60, 2)
        info_o_zadaniach = ""
    else:
        suma_czas_do_skonczenia = 0
        suma_done = 0
        info_o_zadaniach = "DODAJ ZADANIE"



# ----------------- filtrów zadania względem wagi ----------------
    # weight_list = ['minor', 'major', 'critical']
    if request.method == 'POST':
        weight = request.POST.getlist('weight')
        print(weight)
        if weight == ['Minor']:
            print('wybrano minor')
            zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2, weight=0)
            waga = "Minor"
        elif weight == ['Major']:
            zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2, weight=1)
            waga = "Major"
        elif weight == ['Critical']:
            zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2, weight=2)
            waga = "Critical"
        elif weight == ['Minor', 'Major']:
            zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2, weight__lt=2)
            waga = "Minor, Major"
        elif weight == ['Minor', 'Critical']:
            zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2)
            zadania = zadania.exclude(weight=1)
            waga = "Minor, Critical"
        elif weight == ['Major', 'Critical']:
            zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2, weight__gt=0)
            waga = "Major, Critical"

        else:
            zadania = Task.objects.all().filter(projekt=projekt_id, status__lt=2)
            waga = "Wszystkie"

# ------------------- filtruje zadania względem poziomu trudności ---------------------------

        level = request.POST.getlist('level')

        if level == ['Easy']:
            print('wybrano easy')
            zadania = zadania.filter(level=0)
            poziom = "Easy"
        elif level == ['Medium']:
            zadania = zadania.filter(level=1)
            poziom = "Medium"
        elif level == ['Hard']:
            zadania = zadania.filter(level=2)
            poziom = "Hard"
        elif level == ['Easy', 'Medium']:
            zadania = zadania.filter(level__lt=2)
            poziom = "Easy, Medium"
        elif level == ['Easy', 'Hard']:
            zadania = zadania.exclude(level=1)
            poziom = "Easy, Hard"
        elif level == ['Medium', 'Hard']:
            zadania = zadania.filter(level_gt=1)
            poziom = "Medium, Hard"

        else:
            poziom = "Wszystkie"

    contex = {"zadania": zadania, "nr_projektu": projekt_id, "side": "show",
              "time_need": suma_czas_do_skonczenia, "time_done": suma_done, "is_task": info_o_zadaniach,
              "nazwa_projektu": name_of_projekt, "waga": waga, "poziom": poziom}

    return render(request, "main/lista_zadan.html", contex)






def details(request):

    return render(request, "main/details.html")

def add_task(request):
    global no_project
    form = TaskForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.projekt_id = no_project

        obj.save()



        zadania = Task.objects.all().filter(projekt=no_project, status__lt=2)
        contex = {"zadania": zadania, "nr_projektu": no_project, "side": "show"}

zarzadzanie/main/templates/main/add_projekt.html
{% extends 'base.html'%}
{% load static %}

{% block title %}add_projekt{% endblock %}
{% block content %}
<div class="topnav">
  <a href="{% url 'main:start' %}">lista projektów</a>
  <a class="active" href="#contact">Dodawanie projektu</a>
<!--  <a href="#about">About</a>-->
</div>
<br>
<form method="POST" enctype="multipart/form-data">
<h2>Podaj nazwę projektu</h2>
  {% csrf_token %}
  {{ form }}

  <input type="submit" value="Wyślij">
</form>

{% endblock %}

zarzadzanie/main/templates/main/add_task.html
{% extends 'base.html'%}
{% load static %}

{% block title %}TASK{% endblock %}
{% block content %}
<div class="topnav">
  {% if side == "add" %}
    <a href="{% url 'main:start' %}">lista projektów</a>
    <a href="{% url 'main:zadania' numer_projektu %}">Zadania</a>
    <a class="active" href="#contact">dodawanie</a>
  {% else %}
    <a href="{% url 'main:start' %}">lista projektów</a>
    <a href="{% url 'main:zadania' numer_projektu %}">Zadania</a>
    <a class="active" href="#contact">edycja</a>
  {% endif %}
<div>
    {% if user.is_authenticated %}
    <h1 class="display-4"> Witaj {{ user.username }}</h1>
{#    <a href="{% url 'logout' %}" class="btn btn-success">Logout <i class="fas fa-sign-out-alt"></i></a>#}
{% else %}
        <br><div>Nie jesteś zalogowany </div><br>
{% endif %}
</div>
</div>

{% if side == "add" %}
  <div>Dodawanie zadania </div>
{% else %}
  <div>Edytowanie zadania</div>
{% endif %}
<form class="formularz" method="POST" enctype="multipart/form-data">
{% csrf_token %}
<!--  {{ form }}-->
  {{ form.title.label }}<br>{{ form.title}}<br><br>
  {{ form.task.label }}<br>{{ form.task}}<br><br>
  {{ form.branch.label}}<br>{{ form.branch}}<br><br>
  {{ form.weight.label}}<br>{{ form.weight}}<br><br>
  {{ form.level.label}}<br>{{ form.level}}<br><br>
  {{ form.status.label}}<br>{{ form.status}}<br><br>
  {{ form.timeneed.label}}<br>{{ form.timeneed }}<br><br>
  {{ form.timedone.label}}<br>{{ form.timedone}}<br><br>
  {{ form.projekt_id.label}}<br>{{ form.projekt_id}}<br><br>

  <input type="submit" value="Wyślij">
</form>

{% endblock %}

zarzadzanie/main/templates/main/add_users.html
{% extends 'base.html'%}
{% load static %}

{% block title %}add_user{% endblock %}
{% block content %}
<div class="topnav">
  <a href="{% url 'main:start' %}">lista projektów</a>
  <a class="active" href="#contact">Dodawanie użytkownika</a>
<!--  <a href="#about">About</a>-->
</div>
<br>
<form class="formularz" method="POST" enctype="multipart/form-data">
<h2>Podaj swoje dane</h2>
  {% csrf_token %}
  {{ form }}

  <input type="submit" value="Wyślij">
</form>

{% endblock %}

zarzadzanie/main/templates/main/check_task.html
{% extends 'base.html'%}
{% load static %}

{% block title %}show_task{% endblock %}
{% block content %}
<div class="topnav">
  <a href="{% url 'main:start' %}">lista projektów</a>

  <a href="#lista_powrot">Lista zadan</a>
  <a href="#about">About</a>
</div>
    <div>
    {% if user.is_authenticated %}
    <h1 class="display-4"> Witaj {{ user.username }}</h1>
{#    <a href="{% url 'logout' %}" class="btn btn-success">Logout <i class="fas fa-sign-out-alt"></i></a>#}
{% else %}
        <br><div>Nie jesteś zalogowany </div><br>
{% endif %}
</div>
{% for zadanie in zadania %}
  {{ zadanie.title }}<br>
  {{ zadanie.task }}<br>
  {{ zadanie.timeneed}}<br>
  {{ zadanie.status}}
{% endfor %}

{% endblock %}

zarzadzanie/main/templates/main/details.html
{% extends 'base.html'%}
{% load static %}
{% block title %}details{% endblock %}

{% block content %}
<div class="topnav">
  <a href="{% url 'main:start' %}">lista projektów</a>
  <a href="#ddd">Zadania</a>
  <a class="active" href="#contact">edycja</a>

</div>
<h2> Tytuł</h2>



{% endblock %}

zarzadzanie/main/templates/main/lista_zadan.html
{% extends 'base.html'%}
{% load static %}


{% block title %}Lista zadan{% endblock %}
{% block content %}
<div class="topnav">
  <a  href="{% url 'main:start' %}">lista projektów</a>


  {% if side == "delete" %}
    <a   href="{% url 'main:zadania' nr_projektu %}">Zadania</a>
    <a href="{% url 'main:add_task' %}">dodaj zadanie</a>
    <a class="active" href="{% url 'main:delete_task' nr_projektu %}">usun zadanie</a>
    <a href="{% url 'main:done_task' nr_projektu %}">done tasks</a>
  {% elif side == "show" %}
    <a  class="active" href="{% url 'main:zadania' nr_projektu %}">Zadania</a>
    <a href="{% url 'main:add_task' %}">dodaj zadanie</a>
    <a href="{% url 'main:delete_task' nr_projektu %}">usun zadanie</a>
    <a href="{% url 'main:done_task' nr_projektu %}">done tasks</a>
  {% else %}
    <a href="{% url 'main:zadania' nr_projektu %}">Zadania</a>
    <a href="{% url 'main:add_task' %}">dodaj zadanie</a>
    <a href="{% url 'main:delete_task' nr_projektu %}">usun zadanie</a>
    <a class="active"  href="{% url 'main:done_task' nr_projektu %}">done tasks</a>
  {% endif %}
</div>
<form action="" method="post">
    {% csrf_token %}

    <div class="form_check">
        <p>
        <input type="checkbox" value="Minor" id="minor" name="weight">
        <label for="minor">Minor</label>

        <input type="checkbox" value="Major" id="major" name="weight">
        <label for="major">Major</label>

        <input type="checkbox" value="Critical" id="critical" name="weight">
        <label for="critical">Critical</label>
    </p>
    </div>
    <div class="form_check">
        <p>
        <input type="checkbox" value="Easy" id="easy" name="level">
        <label for="easy">Easy</label>

        <input type="checkbox" value="Medium" id="medium" name="level">
        <label for="medium">Medium</label>

        <input type="checkbox" value="Hard" id="hard" name="level">
        <label for="hard">Hard</label>
        </p>
</div>


    <button type="submit">submit</button>

</form>
<div>
    {% if user.is_authenticated %}
    <h1 class="display-4"> Zalogowany jako {{ user.username }}</h1>
{#    <a href="{% url 'logout' %}" class="btn btn-success">Logout <i class="fas fa-sign-out-alt"></i></a>#}
{% else %}
        <br><div>Nie jesteś zalogowany </div><br>
{% endif %}
</div>
<div>
  {% if side == "delete" %}
    Usuwanie zadania <br> Wybierz zadanie do usuniecia
  {% elif side == "show" %}
    Edytowanie zadania <br> Wybierz zadanie do edycji

  {% else %}
    Zakończone zadania
  {% endif %}
  <br><br>
</div>
<hr>
<div class="nazwa-projektu">
  {{ nazwa_projektu }}<br>

</div>
<header>
  {% if side == "done" %}
    <p>Time need {{ suma_timeneed_done }} godzin</p>
    <p>Time done {{ suma_done_done }} godzin</p>
  {% else %}
    <p>Time need {{ time_need }} godzin</p>
    <p>Time done {{ time_done }} godzin</p>
  {% endif %}
Waga: {{ waga }}<br>
Poziom: {{ poziom }}
</header>
<table id="customers">
  <tr>
    <th class="lp">Lp</th>
    <th>Zadania</th>
    <th>Branch</th>
    <th>difficulty</th>
    <th>weight</th>
q    <th>status</th>
    <th>donetime</th>
    <th>needtime</th>
  </tr>
  {% for zadanie in zadania %}
  <tr class="lp">
    <td class="lp">{{ forloop.counter }}</td>
      {% if side == "delete" %}
        <td><a href="{% url 'main:remove_task' zadanie.id %}">{{ zadanie.title }}</a></td>
      {% else %}
        <cos></cos>
        <td><a href="{% url 'main:check_task' zadanie.id %}">{{ zadanie.title }}</a></td>
      {% endif %}


    <td>{{ zadanie.get_branch_display }}</td>


    <td>{{ zadanie.get_level_display }}</td>
    <td>{{ zadanie.get_weight_display }}</td>
    <td>{{ zadanie.get_status_display }}</td>
    <td>{{ zadanie.timedone }}</td>
    <td>{{ zadanie.timeneed }}</td>
  </tr>
  {% endfor %}
</table>
<div class="informacja">
  {{ is_task }}

</div>
{% endblock %}

zarzadzanie/main/templates/main/register.html
{% extends 'base.html'%}
{% load static %}

{% block title %}rejestracja{% endblock %}
{% block content %}


<div class="topnav">
  <a href="{% url 'main:start' %}">lista projektów</a>
  <a class="active" href="#contact">Rejestracja użytkownika</a>
<!--  <a href="#about">About</a>-->
</div>
<br>
    <h1>Rejestracja</h1>
    {%  for message in messages %}
        <p id="messages">{{ message }}</p>
    {%  endfor %}
        <div>
            <form method="post" action="">
                {% csrf_token %}
                {% for field in form %}
                    {{ field.label }}
                    {{ field }}
                    <br><br>
                {% endfor %}
                <input type="submit" value="Zarejestruj">
            </form>
        </div>


{% endblock %}

zarzadzanie/main/templates/main/strona_startowa.html
{% extends 'base.html'%}
{% load static %}


{% block title %}główna{% endblock %}
{% block content %}
<div class="topnav">
  <a class="active" href="{% url 'main:start' %}">lista projektów</a>
  <a href="{% url 'main:add_projekt' %}">Dodaj projekt</a>

<!--  <a href="{% url 'main:details' %}">Contact</a>-->
<!--  <a href="#about">About</a>-->
</div>
<div>
Wybierz projekt
  <br><br>
</div>
<table id="customers">
  <tr>
    <th class="lp">Lp</th>
    <th>Project</th>
    <th>donetime</th>
    <th>needtime</th>
  </tr>

  {% for projekt in projects %}

  <tr class="lp">
    <td class="lp">{{ forloop.counter }}</td>
    <td><a href="{%  url 'main:zadania' projekt.id %}">{{ projekt.project }}</a></td>

  </tr>
  {% endfor %}

</table>


{% endblock %}

zarzadzanie/main/templates/main/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <form action="" method="post">
        {% csrf_token %}
        <div class="form_check">
            <input type="checkbox" value="Minor" id="minor" name="weight">
            <label for="minor">Minor</label>
        </div><div class="form_check">
            <input type="checkbox" value="Major" id="major" name="weight">
            <label for="major">Minor</label>
        </div><div class="form_check">
            <input type="checkbox" value="Critical" id="critical" name="weight">
            <label for="critical">Minor</label>
        </div>
        <button type="submit">submit</button>
    </form>
</body>
</html>